### ISSUE TITLE
Input for `version`

### ISSUE THREAD

**Issue by gbraad** [gbraad-actions/hugo#1]
... this is only possible as a composite:

```yaml
runs:
  using: "composite"
  steps:
    - name: Run Hugo container
      run: |
        docker run ghcr.io/hugomods/hugo:${{ inputs.hugo_version }}
```
